# Generated by Django 5.1.5 on 2025-05-24 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='account_holder_name',
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='payment_upis',
            field=models.CharField(blank=True, null=True),
        ),
    ]
