# Generated by Django 5.1.5 on 2025-04-23 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0002_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='interest',
            field=models.DecimalField(decimal_places=1, default=5.0, max_digits=5),
        ),
    ]
