# Generated by Django 5.1.5 on 2025-05-27 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0002_profile_account_holder_name_profile_payment_upis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='payment_upis',
            field=models.CharField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
