# Generated by Django 5.1.5 on 2025-04-23 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0003_profile_interest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='interest',
            new_name='company_interest',
        ),
    ]
