# Generated by Django 5.1.5 on 2025-07-04 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('repaying', 'Repaying'), ('overdue', 'Overdue'), ('closed', 'Closed'), ('defaulted', 'Defaulted')], default='Repaying', max_length=20)),
                ('total_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('remaining_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('next_due_date', models.DateField(blank=True, null=True)),
                ('last_payment_date', models.DateField(blank=True, null=True)),
                ('closed_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loan_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='activeloan', to='loans.loanrequest')),
            ],
        ),
        migrations.CreateModel(
            name='ReturnPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('online', 'Online')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cash_person', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_app', models.CharField(blank=True, max_length=50, null=True)),
                ('utr', models.CharField(blank=True, max_length=50, null=True)),
                ('due_date', models.DateField(help_text='Due date of the installment')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('returnloan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_payments', to='active_loans.activeloan')),
            ],
        ),
    ]
