# Generated by Django 5.1.5 on 2025-05-20 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('repaying', 'Repaying'), ('overdue', 'Overdue'), ('closed', 'Closed'), ('defaulted', 'Defaulted')], default='repaying', max_length=20)),
                ('total_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('remaining_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('next_due_date', models.DateField(blank=True, null=True)),
                ('last_payment_date', models.DateField(blank=True, null=True)),
                ('closed_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loan_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='loans.loanrequest')),
            ],
        ),
    ]
