# Generated by Django 5.1.5 on 2025-05-24 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('active_loans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeloan',
            name='status',
            field=models.CharField(choices=[('repaying', 'Repaying'), ('overdue', 'Overdue'), ('closed', 'Closed'), ('defaulted', 'Defaulted')], default='Repaying', max_length=20),
        ),
    ]
