# Generated by Django 5.1.5 on 2025-05-27 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('active_loans', '0002_alter_activeloan_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('online', 'Online')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cash_person', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_app', models.CharField(blank=True, max_length=50, null=True)),
                ('utr', models.CharField(blank=True, max_length=50, null=True)),
                ('due_date', models.DateField(help_text='Due date of the installment')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_payments', to='active_loans.activeloan')),
            ],
        ),
    ]
