# Generated by Django 5.1.5 on 2025-06-03 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('active_loans', '0003_returnpayment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='returnpayment',
            old_name='loan',
            new_name='activeloan',
        ),
    ]
