# Generated by Django 5.1.5 on 2025-06-03 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('active_loans', '0004_rename_loan_returnpayment_activeloan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='returnpayment',
            old_name='activeloan',
            new_name='returnloan',
        ),
    ]
