# Generated by Django 5.1.5 on 2025-06-17 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('active_loans', '0005_rename_activeloan_returnpayment_returnloan'),
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeloan',
            name='loan_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='activeloan', to='loans.loanrequest'),
        ),
    ]
