# Generated by Django 5.1.5 on 2025-04-07 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('online', 'Online')], max_length=10)),
                ('cash_from', models.CharField(blank=True, max_length=255, null=True)),
                ('online_method', models.CharField(blank=True, choices=[('phonepe', 'Phone Pay'), ('googlepay', 'Google Pay'), ('paytm', 'Paytm'), ('bank', 'Bank Account')], max_length=20, null=True)),
                ('upi_number', models.CharField(blank=True, max_length=100, null=True)),
                ('upi_screenshot', models.ImageField(blank=True, null=True, upload_to='payment_screenshots/')),
                ('account_number', models.CharField(blank=True, max_length=30, null=True)),
                ('ifsc', models.CharField(blank=True, max_length=20, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('utr', models.CharField(blank=True, max_length=100, null=True)),
                ('person', models.CharField(blank=True, max_length=100, null=True)),
                ('bank', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoanRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=100, unique=True)),
                ('loan_item', models.CharField(max_length=100, null=True)),
                ('amount', models.IntegerField(default=0)),
                ('apply_date', models.DateTimeField(blank=True, null=True)),
                ('taken_date', models.DateField(null=True)),
                ('return_date', models.DateField(null=True)),
                ('referral', models.CharField(blank=True, max_length=255, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('submitted', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('paymentprocess', 'Paymentprocess'), ('paymentdone', 'Paymentdone'), ('paymentreceived', 'Paymentreceived')], default='pending', max_length=20)),
                ('interest', models.DecimalField(decimal_places=1, default=5.0, max_digits=5)),
                ('image', models.ImageField(blank=True, upload_to='loan_items_photos/')),
                ('remark', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('borrower', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='loans.borrower')),
                ('lender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('payment', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='loans.paymentdetail')),
            ],
        ),
    ]
