# Generated by Django 5.1.5 on 2025-04-10 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_remove_loanrequest_image_loanimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanimage',
            name='image',
            field=models.ImageField(upload_to='loan_items_images/'),
        ),
        migrations.AlterField(
            model_name='loanimage',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_item_images', to='loans.loanrequest'),
        ),
    ]
