# Generated by Django 5.1.5 on 2025-04-12 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_alter_loanimage_image_alter_loanimage_loan'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdetail',
            name='account_holder',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
