# Generated by Django 5.1.5 on 2025-04-19 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0005_paymentdetail_account_holder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanrequest',
            name='payment',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_details', to='loans.paymentdetail'),
        ),
    ]
