# Generated by Django 5.1.5 on 2025-04-20 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0006_alter_loanrequest_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanstatushistory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
