# Generated by Django 5.1.5 on 2025-04-23 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0007_alter_loanstatushistory_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrequest',
            name='interest_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='payment_plan',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
