# Generated by Django 5.1.5 on 2025-04-24 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0008_loanrequest_interest_amount_loanrequest_payment_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrequest',
            name='instalment',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
