# Generated by Django 5.1.5 on 2025-04-24 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0009_loanrequest_instalment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanrequest',
            name='instalment',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
