# Generated by Django 5.1.5 on 2025-04-26 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0010_alter_loanrequest_instalment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('paymentprocess', 'Paymentprocess'), ('paymentdone', 'Paymentdone'), ('paymentreceived', 'Paymentreceived'), ('paymentnotreceived', 'Paymentnotreceived')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='loanstatushistory',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('paymentprocess', 'Paymentprocess'), ('paymentdone', 'Paymentdone'), ('paymentreceived', 'Paymentreceived'), ('paymentnotreceived', 'Paymentnotreceived')], max_length=30),
        ),
    ]
